-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.after_joining (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  joining_id text,
  planned_date date,
  actual_date date,
  delay text,
  check_salary_slip_resume boolean DEFAULT false,
  offer_letter_received boolean DEFAULT false,
  welcome_meeting boolean DEFAULT false,
  biometric_access boolean DEFAULT false,
  official_email_id boolean DEFAULT false,
  assign_assets boolean DEFAULT false,
  pf_esic boolean DEFAULT false,
  company_directory boolean DEFAULT false,
  status text DEFAULT 'Pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  emp_id text,
  CONSTRAINT after_joining_pkey PRIMARY KEY (id),
  CONSTRAINT after_joining_joining_id_fkey FOREIGN KEY (joining_id) REFERENCES public.joining_form(joining_id)
);
CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id text NOT NULL UNIQUE,
  employee_name text,
  laptop text,
  mobile text,
  vehicle text,
  sim text,
  email_id text,
  email_password text,
  punch_code text,
  manual text,
  timestamp text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT assets_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.users(emp_id)
);
CREATE TABLE public.attendance_daily (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  emp_id text,
  date date,
  year integer,
  month_name text,
  day text,
  company_name text DEFAULT 'SKAISPAT'::text,
  name text,
  designation text,
  holiday text,
  working_day text,
  n_holiday text,
  status text,
  in_time text,
  out_time text,
  working_hours text,
  present_minutes integer,
  early_out text,
  overtime_hours text,
  punch_miss text,
  remarks text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  daily_pdf_link text,
  CONSTRAINT attendance_daily_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attendance_reports (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  date date NOT NULL,
  pdf_link text NOT NULL,
  time text,
  CONSTRAINT attendance_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attendance_summary (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  year integer,
  month text,
  emp_id text,
  name text,
  designation text,
  company_name text DEFAULT 'SKAISPAT'::text,
  punch_days integer,
  total_on_time integer,
  late_days integer,
  late_not_allowed integer,
  late_allowed integer,
  absent integer,
  punch_miss integer,
  sunday_national_holiday integer,
  total_days integer,
  mgmt_adjustment integer,
  grand_total_days integer,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT attendance_summary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_calender (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  title text NOT NULL,
  date date NOT NULL,
  time text,
  location text,
  type text,
  description text,
  CONSTRAINT company_calender_pkey PRIMARY KEY (id)
);
CREATE TABLE public.employee_enquiry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp with time zone DEFAULT now(),
  indent_number text,
  candidate_enquiry_number text,
  applying_for_post text,
  candidate_name text,
  dob text,
  candidate_phone_number text,
  candidate_email text,
  previous_company_name text,
  job_experience text,
  department text,
  previous_position text,
  reason_of_leaving_previous_company text,
  marital_status text,
  last_employer_mobile_number text,
  candidate_photo text,
  reference_by text,
  present_address text,
  aadhar_number text,
  resume_copy text,
  planned text,
  actual text,
  time_delay text,
  what_did_the_candidate_says text,
  tracker_status text,
  next_call_date text,
  next_planned text,
  next_actual text,
  CONSTRAINT employee_enquiry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.employee_leaving (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  emp_id text NOT NULL,
  reason_of_leaving text,
  date_of_leaving date,
  planned_date date,
  actual_date date,
  final_release_date date,
  resignation_letter_received boolean DEFAULT false,
  resignation_acceptance boolean DEFAULT false,
  handover_assets boolean DEFAULT false,
  cancellation_email_biometric boolean DEFAULT false,
  remove_benefit_enrollment boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT employee_leaving_pkey PRIMARY KEY (id),
  CONSTRAINT employee_exits_emp_id_fkey FOREIGN KEY (emp_id) REFERENCES public.users(emp_id)
);
CREATE TABLE public.gate_pass (
  id integer NOT NULL DEFAULT nextval('gate_pass_id_seq'::regclass),
  timestamp timestamp with time zone,
  serial_no integer,
  emp_id text NOT NULL,
  place_reason_to_visit text,
  departure_from_plant date,
  arrival_at_plant date,
  hod_name character varying,
  employee_whatsapp_number character varying,
  image_gate_pass text,
  status character varying,
  hod_remarks text,
  hr_remarks text,
  hod_id text,
  hr_id text,
  emp_name text,
  hr_name text,
  CONSTRAINT gate_pass_pkey PRIMARY KEY (id),
  CONSTRAINT gate_pass_emp_id_fkey FOREIGN KEY (emp_id) REFERENCES public.users(emp_id)
);
CREATE TABLE public.job_vacancy (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  timestamp timestamp with time zone,
  indent_number text,
  post text,
  gender text,
  department text,
  prefer text,
  number_of_posts integer,
  completion_date date,
  social_site text,
  experience text,
  social_site_types text,
  status text DEFAULT 'NeedMore'::text,
  CONSTRAINT job_vacancy_pkey PRIMARY KEY (id)
);
CREATE TABLE public.joining_form (
  joining_id text NOT NULL,
  name_as_per_aadhar text NOT NULL,
  father_name text NOT NULL,
  date_of_birth date NOT NULL,
  gender text CHECK (gender = ANY (ARRAY['Male'::text, 'Female'::text, 'Other'::text])),
  department text,
  mobile_no text NOT NULL,
  personal_email text,
  family_mobile_no text,
  relationship_with_family text,
  current_address text,
  date_of_joining date NOT NULL,
  designation text,
  highest_qualification text,
  aadhar_card_number text UNIQUE,
  bank_account_no text,
  ifsc_code text,
  branch_name text,
  passport_photo_url text,
  aadhar_card_url text,
  bank_passbook_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT joining_form_pkey PRIMARY KEY (joining_id)
);
CREATE TABLE public.leave_management (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  timestamp timestamp with time zone DEFAULT timezone('utc'::text, now()),
  emp_id text NOT NULL,
  employee_name text NOT NULL,
  designation text,
  leave_type text NOT NULL,
  leave_date_start date NOT NULL,
  leave_date_end date NOT NULL,
  remarks text,
  status text DEFAULT 'Pending'::text,
  hod_name text,
  serial_no bigint,
  hod_remarks text,
  hr_remarks text,
  hod_id text,
  hr_id text,
  hr_name text,
  CONSTRAINT leave_management_pkey PRIMARY KEY (id),
  CONSTRAINT leave_management_emp_id_fkey FOREIGN KEY (emp_id) REFERENCES public.users(emp_id)
);
CREATE TABLE public.leaving (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  timestamp timestamp with time zone DEFAULT now(),
  employee_id text,
  name text,
  date_of_leaving date,
  mobile_number text,
  reason_of_leaving text,
  firm_name text,
  father_name text,
  date_of_joining date,
  work_location text,
  designation text,
  department text,
  planned_date date,
  actual date,
  delay text,
  resignation_letter_received boolean DEFAULT false,
  resignation_acceptance boolean DEFAULT false,
  handover_assets boolean DEFAULT false,
  cancellation_email_biometric boolean DEFAULT false,
  final_release_date date,
  remove_benefit_enrollment boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leaving_pkey PRIMARY KEY (id),
  CONSTRAINT leaving_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.users(emp_id)
);
CREATE TABLE public.logs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  request_id bigint NOT NULL,
  request_type text NOT NULL CHECK (request_type = ANY (ARRAY['Leave'::text, 'Gate Pass'::text])),
  emp_id text NOT NULL,
  emp_name text NOT NULL,
  hod_id text,
  hod_name text,
  hod_action text CHECK (hod_action = ANY (ARRAY['Approved'::text, 'Rejected'::text])),
  hod_approval_time timestamp with time zone,
  hr_id text,
  hr_name text,
  hr_action text CHECK (hr_action = ANY (ARRAY['Approved'::text, 'Rejected'::text])),
  hr_approval_time timestamp with time zone,
  status text,
  details text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  hod_remarks text,
  hr_remarks text,
  CONSTRAINT logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mis_report (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  date_start date,
  date_end date,
  name text,
  target text,
  actual_work_done text,
  weekly_work_done_percent numeric,
  weekly_work_done_on_time_percent numeric,
  total_work_done integer,
  week_pending text,
  all_pending_till_date text,
  CONSTRAINT mis_report_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  recipient_role text,
  recipient_id text,
  sender_id text,
  sender_name text,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  type text,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payroll (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  serial_no integer NOT NULL,
  emp_id text NOT NULL,
  employee_name text,
  designation text,
  days_present integer NOT NULL,
  total_actual numeric NOT NULL,
  basic numeric NOT NULL,
  conveyance numeric NOT NULL,
  hra numeric NOT NULL,
  medical_allowance numeric NOT NULL,
  special_allowance numeric NOT NULL,
  other_allowances numeric NOT NULL,
  loan numeric NOT NULL,
  additional_salary numeric NOT NULL,
  to_be_paid_after_pf numeric NOT NULL,
  year integer NOT NULL,
  month text NOT NULL,
  CONSTRAINT payroll_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_emp_id_fkey FOREIGN KEY (emp_id) REFERENCES public.users(emp_id)
);
CREATE TABLE public.team_members (
  emp_id text NOT NULL,
  hod_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT team_members_pkey PRIMARY KEY (emp_id, hod_id),
  CONSTRAINT team_members_emp_id_fkey FOREIGN KEY (emp_id) REFERENCES public.users(emp_id),
  CONSTRAINT team_members_hod_id_fkey FOREIGN KEY (hod_id) REFERENCES public.users(emp_id)
);
CREATE TABLE public.users (
  emp_id text NOT NULL,
  full_name text NOT NULL,
  designation text,
  department text,
  date_of_birth date,
  gender text,
  joining_date date,
  email text,
  phone_number text,
  emergency_contact text,
  current_address text,
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  role text,
  is_active boolean DEFAULT true,
  profile_picture text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  is_hod boolean DEFAULT false,
  page_access ARRAY DEFAULT '{}'::text[],
  hod_id text,
  is_leave_allowed boolean DEFAULT true,
  CONSTRAINT users_pkey PRIMARY KEY (emp_id),
  CONSTRAINT users_hod_id_fkey FOREIGN KEY (hod_id) REFERENCES public.users(emp_id)
);